<?php

namespace AppBundle\Repository;

/**
 * GuideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AwardGuideRepository extends \Doctrine\ORM\EntityRepository
{


    public function awardGuideYearSearch($year)
    {
        //je passe en variable la wildcard year
        //on utlise le query builder qui nous permet de créér des requêtes en base de données
        // pour la table YearOld (on est dans YearOldRepository) (usine à requete sql)
        //On appelle la méthode 'createQueryBuilder' qui renvoie une classe qui nous permet de créer
        // des requetes en base de données pour la table WineCastle (on est dans EventsRepository)
        $qb = $this->createQueryBuilder('ag');
        //par convention, on met juste une lettre mais on aurait pu mettre event
        // en cas de jointure avec 2 classes començant avec un e, on peut par convention mettre ev

        //correction:
        // je créé ma requete sql en utilisant les méthodes de Doctrine, qui ressemble à du sql
        //et qui sont traduites par Doctrine en SQL
        //Cette requete vient récupérer dans la table WineCastle tous les noms dont la category est égale à $nameCastle
        $query = $qb->select('ag')
            ->where('ag.year=:year')//setParameter equivalent au bindparameter en PDO, permet de gérer la sécurité et d'échapper les caractères indésirables (ex: param de commande)
            ->setParameter('year', $year)//on interroge sur la variable
            ->getQuery();
        //je récupère les résultats de ma requete
        $results = $query->getArrayResult();
        var_dump($results);
        die;

    }

    public function searchValueYear($variable){
        $qb=$this->createQueryBuilder('ag');
        $query=$qb->select('ag')
            ->where('ag.year LIKE :year')
            ->setParameter('variable','%'.$variable.'%')
            ->getQuery();
        return $results=$query->getArrayResult();
    }

    public function awardGuideNameSearch($guideName)
    {
        //je passe en variable la wildcard year
        //on utlise le query builder qui nous permet de créér des requêtes en base de données
        // pour la table YearOld (on est dans YearOldRepository) (usine à requete sql)
        //On appelle la méthode 'createQueryBuilder' qui renvoie une classe qui nous permet de créer
        // des requetes en base de données pour la table WineCastle (on est dans EventsRepository)
        $qb = $this->createQueryBuilder('ag');
        //par convention, on met juste une lettre mais on aurait pu mettre event
        // en cas de jointure avec 2 classes començant avec un e, on peut par convention mettre ev

        //correction:
        // je créé ma requete sql en utilisant les méthodes de Doctrine, qui ressemble à du sql
        //et qui sont traduites par Doctrine en SQL
        //Cette requete vient récupérer dans la table WineCastle tous les noms dont la category est égale à $nameCastle
        $query = $qb->select('ag')
            ->where('ag.guideName=:guideName')//setParameter equivalent au bindparameter en PDO, permet de gérer la sécurité et d'échapper les caractères indésirables (ex: param de commande)
            ->setParameter('guideName', $guideName)//on interroge sur la variable
            ->getQuery();
        //je récupère les résultats de ma requete
        $results = $query->getArrayResult();
        var_dump($results);
        die;

    }

    public function searchValueGuideName($variable){
        $qb=$this->createQueryBuilder('ag');
        $query=$qb->select('ag')
            ->where('ag.guideName LIKE :guideName')
            ->setParameter('variable','%'.$variable.'%')
            ->getQuery();
        return $results=$query->getArrayResult();
    }

}

