<?php

namespace AppBundle\Repository;

/**
 * AuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuteursRepository extends \Doctrine\ORM\EntityRepository
{


    public function auteurNameSearch($name)
    {
        //je passe en variable la wildcard name
        //on utlise le query builder qui nous permet de créér des requêtes en base de données
        // pour la table Auteur (on est dans AuteursRepository) (usine à requete sql)
        //On appelle la méthode 'createQueryBuilder' qui renvoie une classe qui nous permet de créer
        // des requetes en base de données pour la table Auteur (on est dans AuteursRepository)
        $qb = $this->createQueryBuilder('au');
        //par convention, on met juste une lettre mais on aurait pu mettre book
        // en cas de jointure avec 2 classes començant avec un b, on peut par convention mettre bo

        //correction:
        // je créé ma requete sql en utilisant les méthodes de Doctrine, qui ressemble à du sql
        //et qui sont traduites par Doctrine en SQL
        //Cette requete vient récupérer dans la table Auteur tous les noms dont la category est égale à $name
        $query = $qb->select('au')
            ->where('au.name=:name')//setParameter equivalent au bindparameter en PDO, permet de gérer la sécurité et d'échapper les caractères indésirables (ex: param de commande)
            ->setParameter('name', $name)//on interroge sur la variable
            ->getQuery();
        //je récupère les résultats de ma requete
        $results = $query->getArrayResult();
        var_dump($results);
        die;

    }

    public function searchWordName($variable){
        $qb=$this->createQueryBuilder('au');
        $query=$qb->select('au')
            ->where('au.name LIKE :variable')
            ->setParameter('variable','%'.$variable.'%')
            ->getQuery();
        return $results=$query->getArrayResult();
    }


}

